# Generated by Django 6.1 on 2026-08-31 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ф. И. О.')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('compaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='compaigns.compaign', verbose_name='Рекламная кампания')),
            ],
            options={
                'verbose_name': 'Потенциальный клиент',
                'verbose_name_plural': 'Потенциальные клиенты',
            },
        ),
    ]
