# Generated by Django 6.1 on 2026-08-31 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('channel', models.CharField(choices=[('social', 'Социальные сети'), ('context', 'Контекстная реклама'), ('targeting', 'Таргетированная реклама'), ('email', 'Email-рассылка'), ('other', 'Другое')], max_length=50, verbose_name='Канал продвижения')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Бюджет на рекламу')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compaigns', to='services.service', verbose_name='Рекламируемая услуга')),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
            },
        ),
    ]
