# Generated by Django 6.1 on 2026-08-31 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='contracts/', verbose_name='Файл с документом')),
                ('conclusion_date', models.DateField(verbose_name='Дата заключения')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
